name: Trunk Code Quality Check
on: [pull_request]
concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

permissions: read-all

jobs:
    trunk_check:
        name: Trunk Code Quality Runner
        runs-on: blacksmith-2vcpu-ubuntu-2404 # trunk-ignore(actionlint/runner-label)
        permissions:
            checks: write # For trunk to post annotations
            contents: read # For repo checkout

        steps:
            - name: Checkout
              uses: actions/checkout@v4 # zizmor: ignore[unpinned-uses]
              with:
                  persist-credentials: false

            - name: Trunk Code Quality
              uses: trunk-io/trunk-action@v1 # zizmor: ignore[unpinned-uses]
